# Generated by Django 3.1.7 on 2021-04-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_postitnote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostItNote',
            new_name='Postit',
        ),
    ]
