# Generated by Django 3.1.7 on 2021-04-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210401_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
    ]
