# Generated by Django 3.1.7 on 2021-04-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210402_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={},
        ),
    ]
